### PR TITLE
Update 6.md

### PR DESCRIPTION
**Pull request by jrnt30**
Not entirely sure what level of specificity you are going for, but as someone typing it in myself as I was following along, found there to be a few things missing in the deltas that took a bit of investigation.

### CODE REVIEW

**Review by lorensr — APPROVED** [review]
Thanks Justin—we definitely appreciate PRs with gaps in code snippets. While I tried to not repeat imports, I do want them included the first time they're needed in a file!

Will merge once we have a CLA set up ☺️

**Comment by jrnt30** [comment]
Sounds great, keep up the good work on the book!

**Comment by lorensr** [comment]
@jrnt30 got the contributor agreement! Would you mind please signing? https://cla-assistant.io/GraphQLGuide/book?pullRequest=8

**Comment by jrnt30** [comment]
All done.

**Pull request merged**
